const syllabus = {
  // JEE: {
  //   Physics: [
  //     "Kinematics",
  //     "Work, Power, and Energy",
  //     "Rotational Motion",
  //     "Gravitation",
  //     "Electrostatics",
  //     "Current Electricity",
  //     "Magnetism",
  //     "Optics",
  //     "Modern Physics",
  //   ],
  //   Chemistry: [
  //     "Atomic Structure",
  //     "Chemical Bonding",
  //     "Thermodynamics",
  //     "Equilibrium",
  //     "Electrochemistry",
  //     "Organic Chemistry",
  //     "Hydrocarbons",
  //     "Aromatic Compounds",
  //   ],
  //   Mathematics: [
  //     "Quadratic Equations",
  //     "Sequences and Series",
  //     "Binomial Theorem",
  //     "Straight Lines",
  //     "Conic Sections",
  //     "Vectors",
  //     "3D Geometry",
  //     "Integration",
  //     "Differential Equations",
  //   ],
  // },
  // NEET: {
  //   Physics: [
  //     "Physical World",
  //     "Laws of Motion",
  //     "Work, Power and Energy",
  //     "Thermodynamics",
  //     "Current Electricity",
  //     "Optics",
  //     "Modern Physics",
  //   ],
  //   Chemistry: [
  //     "Some Basic Concepts of Chemistry",
  //     "Structure of Atom",
  //     "Chemical Bonding",
  //     "Thermodynamics",
  //     "Equilibrium",
  //     "Organic Chemistry",
  //     "Biomolecules",
  //   ],
  //   Biology: [
  //     "Cell: Structure and Function",
  //     "Plant Physiology",
  //     "Human Physiology",
  //     "Genetics and Evolution",
  //     "Biotechnology",
  //     "Human Health and Disease",
  //     "Ecology and Environment",
  //   ],
  // },
};

export default syllabus;
